name: Container

on:
  push:
    tags:
      - "*"

env:
  project: MyWeb

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      - name: Build docker
        run: |
          docker build -f docker/Dockerfile -t wk-j/${{ project }}:${{ steps.get-version.outputs.VERSION }} .
      - uses: azure/container-scan@v0
        with:
          image-name: wk-j/${{ env.project }}:${{ steps.get-version.outputs.VERSION }}
