name: Build

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.201

      - name: Get the version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

      # - name: Build client
      #   run: |
      #     npm --prefix src/Client install
      #     npm --prefix src/Client run publish

      - name: Build backend
        run: |
          dotnet publish src/MyWeb  -o __publish__/MyWeb -r win-x64
          (cd __publish__; zip -r MyWeb.zip MyWeb)

      - name: Upload Caat
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: __publish__/MyWeb.zip
          asset_name: MyWeb.${{ steps.get-version.outputs.VERSION }}.zip
          tag: ${{ github.ref }}
          overwrite: true
